### ISSUE TITLE
ridership.txt files

### ISSUE THREAD

**Issue by PPaulsonOregonDOT** [ODOT-PTS/GTFS-ride#10]
In the spec, ridership.txt lists all of the GTFS identifiers (agency_id, route_id) are all listed as optional. If we don't have at least one of those fields filled in, is this useful?

**Comment by carletop** [comment]
The ridership standard has been designed to support multi-agency GTFS feeds, therefore, ridership counts in [*ridership.txt*](https://github.com/ODOT-PTS/GTFS-ride/blob/master/spec/en/reference.md#ridershiptxt) without any associated GTFS identifiers would indicate aggregated counts over all services specified in the associated GFTS feed files over the indicated date range.

**Comment by hooversy** [comment]
The [Wiki entry for ridership.txt](https://github.com/ODOT-PTS/GTFS-ride/wiki/GTFS%E2%80%90ride-Files#ridershiptxt) was modified to include the clarification. Thank you for bringing the potential ambiguity to our attention.
