### ISSUE TITLE
Sampled Ridership

### ISSUE THREAD

**Issue by 3vivekb** [ODOT-PTS/GTFS-ride#14]
So at the VTA our APCS are only on around 60% of the buses.  Would it fit in this spec?  Perhaps we create a board_alight file but not a ridership file?

**Comment by hooversy** [comment]
Greetings,

Mixed data sourcing can be easily accommodated in GTFS-ride. For APC collected data, `board_alight.txt` is usually your best choice. For busses w/o APCs, if you have trip or route level ridership counts then `ridership.txt` would be used. It's fine to have some trips with APC data in `board_alight.txt` and other trips with more aggregate data in `ridership.txt`.  `ridership.txt` can also be used to provide aggregated ridership data for scales (trip, route, system; peak hours, multiple-days, etc.) not possible to represent in `board_alight.txt`. For trips without ridership counts, there's no need to include them in any of the ridership data files. 

I'm going to close out the issue, but feel free to contact me directly if you have any more questions or are interested in talking more about using GTFS-ride at VTA.

Thanks,
Sylvan

**Comment by 3vivekb** [comment]
I agree this issue should be closed.

Perhaps you can make a quick guide for the different agencies data types: My agency has this what do I do?

Then people can focus only on the parts of the spec that concerns them and they don't get lost in the weeds.
