### ISSUE TITLE
trip_capacity.txt --> replace with vehicle characteristics table?

### ISSUE THREAD

**Issue by antrim** [ODOT-PTS/GTFS-ride#19]
@MobilityData ([MobilityData.org](http://mobilitydata.org)) currently has a draft proposal to describe vehicle type characteristics. I am seeking to share this proposal with the GTFS-ride group.

GTFS-ride could reference these vehicle type characteristics instead of describing this in trip_capacity. Vehicles types could then be linked to trips or blocks.

**Comment by antrim** [comment]
The proposed [GTFS-Vehicles extension](http://bit.ly/gtfs-vehicles) by @LeoFrachet might be useful to reference. We expect that a version of this will be accepted into the GTFS. Then GTFS-ride should reference this.

The GTFS-Vehicles extension includes these sub-extensions:

* **GTFS-Vehicles** describes the vehicles themselves (e.g. Does the vehicle have A/C? Is there a ramp for riders in wheelchair? Is the bus full?). This extension is the core of the proposal and is required for every other extension.
* **GTFS-VehicleCouplings** describes the coupling of vehicles into composed vehicles like trains (e.g. Which carriage is the restaurant carriage? Which one is First Class? In which one can I go with a wheelchair?).
* **GTFS-VehicleBoardings** describes where the vehicle stops on a platform (e.g. Where should I wait on the platform? Combined with VehicleCouplings, this tells where will stop my carriage, or in which carriage I should to alight in front of the exit).
* **GTFS-VehicleDoors** describes the properties of each door of a vehicle (e.g. Can we board or alight at this door? Is this door wheelchair accessible?).

**Comment by carletop** [comment]
Has this extension been accepted as an official part of GTFS? I agree that, if it has become an industry standard, it will make sense for GTFS-ride to reference these IDs as opposed to having its own parallel description. Would you like to create the official pull request for the sought changes in _trip_capacity.txt_?

**Comment by carletop** [comment]
I'll close this for now. I'd suggest planning to start a pull request if and when the proposed extensions come to fruition.

**Comment by antrim** [comment]
Can you reopen and assign to me?
