### ISSUE TITLE
Make service_date a required field

### ISSUE THREAD

**Issue by dmani** [ODOT-PTS/GTFS-ride#26]
Service_date in board_alight.txt could be changed to a required field as the trip_id alone is not sufficient to identify the date of travel.

**Comment by carletop** [comment]
You are correct. Any ridership data without a **service_date** would be assumed to be aggregated over all the active days in the trips associated **service_id**. The original intent was to offer flexibility, but as you indicate, others may desire that specificity be a requirement for consistency. Also requiring a date may be confusing when the purpose of _board_alight.txt_ is to record service cancelation information as indicated by a 1 in **record_use** (the other existing required fields could also be issues for clarity in this case). @dmani What is your understanding of an agencies desires, to prioritize flexibility or consistent, high-resolution data?

**Comment by carletop** [comment]
@dmani I will close this issue for now, but if you feel it's unresolved I'll reopen it.
