### ISSUE TITLE
Vehicle_id in trip_capacity.txt

### ISSUE THREAD

**Issue by dmani** [ODOT-PTS/GTFS-ride#27]
An optional vehicle_id field could be added to trip_capacity.txt. This could be referenced by the [GTFS-RT](https://developers.google.com/transit/gtfs-realtime/reference/#message-vehicledescriptor) (real-time) feed.

**Comment by carletop** [comment]
@dmani Do you have thoughts on the suggestion from @antrim in issue #19?

**Comment by carletop** [comment]
I will hold off creating a pull request for the suggested change pending the activity under issue #19. This can be reopened if a resolution to issue #19 does not address this issue.
