### ISSUE TITLE
GTFS-ride Wiki Google Groups bad link

### ISSUE THREAD

**Issue by botanize** [ODOT-PTS/GTFS-ride#28]
The wiki links to https://groups.google.com/forum/#!forum/gtfs-ride-changes, but no group exists. The correct group is: https://groups.google.com/forum/#!forum/gtfs-ride

**Comment by carletop** [comment]
The link has been updated. Thank you for catching this. We changed the group name to also include general GTFS-ride discussion but missed updating this link.
