### ISSUE TITLE
`arriving_load` more useful than `current_load` in `board_alight.txt`

### ISSUE THREAD

**Issue by e-lo** [ODOT-PTS/GTFS-ride#3]
The load for the arriving bus is more useful to people at the stop than the load as it leaves the stop.   Suggest replacing `current_load` with `arriving_load`.

**Comment by hooversy** [comment]
Agree that the arriving load is more useful to people at the stop, and see GTFS-Realtime's OccupancyStatus as an excellent tool for agencies to communicate that information to their riders. Our intent is for agencies and organizations to use GTFS-ride to analyze their ridership, with feedback received indicating a preference for departing load. With such intent, does `current_load`, as it is now, make sense?

**Comment by e-lo** [comment]
I would presume that it would be useful to be consistent with GTFS-Realtime.  Maybe it should be optional for either one.

**Comment by hooversy** [comment]
We're already out of step w/ GTFS-Realtime in anticipating a numeric value (had left open as to whether to be absolute, percentage, or other; though clarification is increasingly looking like it is due). From the perspective of later analysis, are there specific gains of arriving load vs. departing load? I'm asking the same question of those advocating departing load as support for that measure was all we had heard prior to your comment, so we specified w/o further consideration.

**Comment by e-lo** [comment]
> Are there specific gains of arriving load vs. departing load? 
From my perspective, yes.  I do a lot of analysis on the effects of crowded vehicles.  The load approaching a stop is more relevant for the ridership activity that happens at that stop.  

For example, if there is a heavy load some drivers simply pass up all the waiting passengers.  In other instances, it creates extremely prolonged dwell times because of the friction.

**Comment by hooversy** [comment]
Excellent. I will share this with the team here and we will implement a means for such information to be represented.

**Comment by hooversy** [comment]
Possible solution in [`ae9cac7`](https://github.com/ODOT-PTS/GTFS-ride/commit/ae9cac7b9b127d86b1e0da206b71b4de63218f2e).

**Comment by hooversy** [comment]
I'm going to close out this issue. The solution in  [`ae9cac7`](https://github.com/ODOT-PTS/GTFS-ride/commit/ae9cac7b9b127d86b1e0da206b71b4de63218f2e) has been included as we are preparing for the release of the standard. It is an integral element of [`board_alight.txt`](https://github.com/ODOT-PTS/GTFS-ride/blob/master/spec/en/reference.md#board_alighttxt), and I'm excited to see how such data will be used to better understand crowding and associated ridership.
