### ISSUE TITLE
Bike boards/alights: inside or in front?

### ISSUE THREAD

**Issue by e-lo** [ODOT-PTS/GTFS-ride#4]
bike boards/alights are ambiguous about whether the bike is inside or not.  Suggest being specific.

**Comment by hooversy** [comment]
Agreed, and change committed directly to master branch. `The bike_* field contains the number of bike alightings at the identified stop and trip. This value represents both bikes racked externally and bikes brought inside the passenger compartment.` Not wanting to increase total fields, the team opted to keep current attributes but clarify breath in the description.
